on: push
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Bogdanp/setup-racket@v1.7
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: "CS"
        version: "8.4"
        local_catalogs: $GITHUB_WORKSPACE
        dest: '/opt/racketdist'
        sudo: never
    - name: Install pkgs and deps
      run: raco pkg install --batch --auto gillette-lib/ gillette-doc/ gillette-test/ gillette/
    - name: Run package-internal tests
      run: raco test -j 4 gillette-lib/
    - name: Run package-external tests
      run: raco test -j 4 gillette-test/
